project_trop_de/consumption/urls.py
from django.urls import path

from . import views


app_name = "consumption"
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:consumption_id>", views.consumption, name="consumption"),
]

project_trop_de/project_trop_de/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("consumption/", include("consumption.urls")),
    path("admin/", admin.site.urls),
]

project_trop_de/consumption/models.py
from django.db import models


class TypeOf(models.Model):
    """salt, alcohol, water, protein, bière, tofu """
    typeof_name = models.CharField(max_length=250)

    def __str__(self):
        return f"{self.typeof_name}"


class Amount(models.Model):
    """25, 33, 50 """
    amount_name = models.IntegerField()

    def __str__(self):
        return f"{self.amount_name}"


class Unit(models.Model):
    """ml, cl, mg """
    unit_name = models.CharField(max_length=250)

    def __str__(self):
        return f"{self.unit_name}"


class Percentage(models.Model):
    """ 0.00 - 25.00 but fill it in as you go """
    percentage = models.DecimalField(max_digits=3, decimal_places=1)

    def __str__(self):
        return f"{self.percentage}"


class Consumption(models.Model):
    """ the consumption """
    consumption_date = models.DateTimeField("date of consumption")
    number_of = models.IntegerField()
    amount = models.ForeignKey(
        Amount,
        on_delete=models.DO_NOTHING,
    )
    unit = models.ForeignKey(
        Unit,
        on_delete=models.DO_NOTHING,
    )
    type_of = models.ForeignKey(
        TypeOf,
        on_delete=models.DO_NOTHING,
    )
    percentage = models.ForeignKey(
        Percentage,
        on_delete=models.DO_NOTHING,
    )
    nom = models.CharField(max_length=500)

    def __str__(self):
        return f"{self.nom}"

project_trop_de/consumption/views.py
from django.shortcuts import (
    render,
    get_object_or_404,
)

from .models import Consumption


def index(request):
    consumptions = Consumption.objects.order_by("-consumption_date")
    context = dict(consumptions=consumptions)
    return render(request, "consumption/index.html", context)


def consumption(request, consumption_id):
    consumption = get_object_or_404(Consumption, pk=consumption_id)
    context = dict(consumption=consumption)
    return render(request, "consumption/detail.html", context)

project_trop_de/consumption/templates/consumption/detail.html
<h1>{{ consumption.nom }}</h1>
<h2>{{ consumption.consumption_date }}</h2>
<h3>{{ consumption.number_of }}</h3>
<h3>{{ consumption.amount }}{{ consumption.unit }}</h3>
<h3>{{ consumption.type_of }}</h3> 
<h3>{{ consumption.percentage }}</h3>    

project_trop_de/consumption/templates/consumption/index.html
{% if consumptions %}
    {% for consumption in consumptions %}
    <div class="consumption">
	    <a href="{% url 'consumption:consumption' consumption.id %}">{{ consumption.consumption_date }} - {{ consumption.nom }}</a>
    </div>
    {% endfor %}
{% else %}
<div class="consumption">No consumptions</div>
{% endif %}